### ISSUE TITLE
Crash upon first run (second run worked)

### ISSUE THREAD

**Issue by opusforlife2** [cyanomiko/dcnnt-android#10]
Hi. Immediately upon opening the app after installing it, I got this crash:

```
FATAL EXCEPTION: main
Process: net.dcnnt, PID: 31438
java.lang.RuntimeException: Unable to create application net.dcnnt.core.App: java.io.FileNotFoundException: /data/user/0/net.dcnnt/log/dcnnt.0.work.log: open failed: ENOENT (No such file or directory)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.io.FileNotFoundException: /data/user/0/net.dcnnt/log/dcnnt.0.work.log: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at a.a.g.i.a(Unknown Source:5)
	at a.a.g.i.<init>(Unknown Source:83)
	at net.dcnnt.core.App.onCreate(:5)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
	... 8 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 14 more
```

**Comment by cyanomiko** [comment]
Thanks for report! I suppose, 02e526936dfd43bb229c0caa61faf8965a9a2df9 will fix it.
