### ISSUE TITLE
app crashing when entering notifications area

### ISSUE THREAD

**Issue by josevega96** [cyanomiko/dcnnt-android#8]
Don't know if it's because I'm using this on Android 11 but when I try to access the notification section in the app it crases, here's the error I'm getting hope this helps 

`android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8809)
	at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:4612)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:962)
	at android.view.View.setFlags(View.java:16122)
	at android.view.View.setEnabled(View.java:11744)
	at android.widget.TextView.setEnabled(TextView.java:2259)
	at a.a.a.b$b.a(:4)
	at i.h.a.run(Unknown Source:2)`

**Comment by raspbeguy** [comment]
Can confirm this bug. Also using Android 11.

**Comment by G-i-o** [comment]
Hi. As of today, I can confirm I've got the same issue.

• App Version: Device Connect v0.6.2
• OS Version: Lineage 17.1 (Based on Android 10).

:pray:

**Comment by cyanomiko** [comment]
Thanks for reports! Found possible cause and fix it: eaa8da1f3937da9fe4394860d46c28abb8765d1e

**Comment by G-i-o** [comment]
Thank You! Looking forward to it. Will keep an eye
on F-Droid for when ready.

Keep up the good work!

**Comment by cyanomiko** [comment]
Android 11 restricts access to list of installed packages. Added permission to manifest. Maybe it will help.

**Comment by josevega96** [comment]
yep, it helped can confirm i can see all my apps now , thanks a lot!
